// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj8WCGrsL1L62KDZkHONE_bEVPGHtvz4U',
    appId: '1:842807314099:web:43b6a97ba48a63ce8fd2c6',
    messagingSenderId: '842807314099',
    projectId: 'interiorcoffee-54622',
    authDomain: 'interiorcoffee-54622.firebaseapp.com',
    storageBucket: 'interiorcoffee-54622.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGFUSI7O06FT3Rtztpe852xX3kpW92K80',
    appId: '1:842807314099:android:44ac6d374b40ca088fd2c6',
    messagingSenderId: '842807314099',
    projectId: 'interiorcoffee-54622',
    storageBucket: 'interiorcoffee-54622.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFqracPbacUHHst9iOjwEQbGkQqc91pqI',
    appId: '1:842807314099:ios:4102709ff6dd08c78fd2c6',
    messagingSenderId: '842807314099',
    projectId: 'interiorcoffee-54622',
    storageBucket: 'interiorcoffee-54622.appspot.com',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFqracPbacUHHst9iOjwEQbGkQqc91pqI',
    appId: '1:842807314099:ios:4102709ff6dd08c78fd2c6',
    messagingSenderId: '842807314099',
    projectId: 'interiorcoffee-54622',
    storageBucket: 'interiorcoffee-54622.appspot.com',
    iosBundleId: 'com.example.interiorCoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj8WCGrsL1L62KDZkHONE_bEVPGHtvz4U',
    appId: '1:842807314099:web:bef87de816b66dbf8fd2c6',
    messagingSenderId: '842807314099',
    projectId: 'interiorcoffee-54622',
    authDomain: 'interiorcoffee-54622.firebaseapp.com',
    storageBucket: 'interiorcoffee-54622.appspot.com',
  );
}
